### ISSUE TITLE
Fix the game pieces to work responsively.

### ISSUE THREAD

**Issue by KrystalJean** [BuddieChapman/connect4#2]
The game pieces do not move well with the cursor.  At certain screen sizes the gamepiece/tokens move before the cursor reaches them.  Would you want to tackle this @BuddieChapman?

**Comment by BuddieChapman** [comment]
The tokens are now placed in the correct columns for all window sizes.

Fixed with commit 70487b7a81170d62ec6a0c93c1a5473a62ff9b1e

**Comment by KrystalJean** [comment]
Do I need to open a pull request to get these changes down to my local machine, because I am trying git fetch origin, and git pull origin master, but in VSC the game pieces were still moving weird?
